// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkrtzigdurysufsyklms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrcnR6aWdkdXJ5c3Vmc3lrbG1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTI4MjAsImV4cCI6MjA2MTQyODgyMH0.4BLYZPedvwcgMbAEpwibzMFsvdQCZ-HysHkn6daeRos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);